#!/usr/bin/env bash
# -*- coding: utf-8 -*-
#
# Script: tests/align_fastqs/scripts/make_fixtures.sh
#
# Copyright 2026 by Kris Alavattam
# Email: kalavattam@gmail.com
#
# OpenAI ChatGPT (GPT-5.5) was used in development.
#
# Distributed under the MIT license.


#  Require Bash >= 4.4 before doing any work
if [[ -z "${BASH_VERSION:-}" ]]; then
    echo "error(shell):" \
        "this script must be run under Bash >= 4.4." >&2
    exit 1
elif ((
    BASH_VERSINFO[0] < 4 || ( BASH_VERSINFO[0] == 4 && BASH_VERSINFO[1] < 4 )
)); then
    echo "error($(basename "${BASH_SOURCE[0]}")):" \
        "this script requires Bash >= 4.4; current version is" \
        "'${BASH_VERSION}'." >&2
    exit 1
fi

#  Run in safe mode, exiting on errors, unset variables, and pipe failures
set -euo pipefail


#  Resolve paths relative to 'tests/align_fastqs/scripts'
dir_scr="$(cd "$(dirname "${BASH_SOURCE[0]}")" > /dev/null 2>&1 && pwd)"
dir_aln="$(cd "${dir_scr}/.." > /dev/null 2>&1 && pwd)"
dir_fix="${dir_aln}/fixtures"

dir_ref="${dir_fix}/reference"
dir_fq="${dir_fix}/fastq"
dir_bt2="${dir_fix}/bowtie2"

fil_ref="${dir_ref}/tiny.fa"
fil_fq_se="${dir_fq}/tiny_se.atria.fastq"
fil_fq_se_gz="${fil_fq_se}.gz"
idx_bt2="${dir_bt2}/tiny"
fil_read="${dir_fix}/README.md"

env_req="env_protocol"


#  Check that the project environment is active before writing fixtures
if [[ "${CONDA_DEFAULT_ENV:-}" != "${env_req}" ]]; then
    echo "error($(basename "${BASH_SOURCE[0]}")):" \
        "activate '${env_req}' before generating align-fastqs fixtures;" \
        "current environment: '${CONDA_DEFAULT_ENV:-none}'." >&2
    exit 1
fi


#  Require alignment tools used to generate and validate fixtures
for cmd in bowtie2 bowtie2-build bowtie2-inspect gzip samtools; do
    if ! command -v "${cmd}" > /dev/null 2>&1; then
        echo "error($(basename "${BASH_SOURCE[0]}")):" \
            "'${cmd}' must be available in '${env_req}' to generate" \
            "align-fastqs fixtures." >&2
        exit 1
    fi
done
unset cmd


#  Create fixture output directories
mkdir -p \
    "${dir_ref}" \
    "${dir_fq}" \
    "${dir_bt2}"


#  Write tiny reference FASTA used for Bowtie2 alignment tests
cat > "${fil_ref}" << 'EOM'
>I
GATCGTACCTAGGCTAACGTTGACCGTTAACGATCGTAGCTAGGATCCGTTACGATCGATGCTAGCTTACCGGATCAAGCTTAGGCTAATCGGCTAAGGTTCCGATTA
EOM


#  Write tiny single-end FASTQ provenance and compressed input fixture
cat > "${fil_fq_se}" << 'EOM'
@tiny_se_read_1
ACGTTGACCGTTAACGATCGTAGCTAGGAT
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIII
EOM

gzip -n -c "${fil_fq_se}" > "${fil_fq_se_gz}"


#  Generate and validate Bowtie2 index files
rm -f "${idx_bt2}".*.bt2 "${idx_bt2}".*.bt2l
bowtie2-build "${fil_ref}" "${idx_bt2}" > /dev/null

bowtie2-inspect -n "${idx_bt2}" > /dev/null

bowtie2 \
    -x "${idx_bt2}" \
    -U "${fil_fq_se_gz}" \
    -S /dev/null \
        > /dev/null \
        2> /dev/null


#  Write fixture documentation
cat > "${fil_read}" << 'EOM'
# Align-fastqs test fixtures
These fixtures are synthetic micro-fixtures for fast, deterministic tests of the align-fastqs workflow.

They are intentionally small, hand-checkable, and version-controlled directly in Git. Running `scripts/make_fixtures.sh` from `env_protocol` regenerates the fixture set deterministically.

The first fixture batch focuses on single-end Bowtie2 alignment to BAM output. These fixtures are not derived from real sequencing data. The reference and FASTQ provenance were written by hand so that the expected mapped read is easy to inspect.

<br />

## Files
Readable provenance:
- `reference/tiny.fa`
- `fastq/tiny_se.atria.fastq`

Compressed FASTQ input:
- `fastq/tiny_se.atria.fastq.gz`

Bowtie2 index:
- `bowtie2/tiny.1.bt2`
- `bowtie2/tiny.2.bt2`
- `bowtie2/tiny.3.bt2`
- `bowtie2/tiny.4.bt2`
- `bowtie2/tiny.rev.1.bt2`
- `bowtie2/tiny.rev.2.bt2`

The compressed FASTQ and Bowtie2 index files are generated by `scripts/make_fixtures.sh`. They are committed because align/trim/download workflows commonly operate on compressed FASTQ inputs and real aligner indexes.

<br />

## Expected alignment behavior
The single-end FASTQ fixture contains one read:

| Read name        | Sequence                         | Expected reference |
|:---              |:---                              |:---                |
| `tiny_se_read_1` | `ACGTTGACCGTTAACGATCGTAGCTAGGAT` | `I`                |

Bowtie2 should align this read to chromosome `I` in the tiny reference. Smoke tests should verify that wrapper-generated BAM files and BAM indexes exist, pass `samtools quickcheck`, report one mapped read on `I` with `samtools idxstats`, and contain the expected read name.

<br />

## Deferred fixture batches
Later align-fastqs batches should add paired-end FASTQ fixtures, CRAM/reference-propagation coverage, BWA MEM indexes, bwa-mem2 MEM indexes, BWA ALN indexes, and local GNU Parallel coverage.
EOM

echo "success($(basename "${BASH_SOURCE[0]}")):" \
    "generated align-fastqs fixtures under '${dir_fix}'."
